// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyUpdate():Promise<void>;

export function BroadcastChat(arg1:string):Promise<void>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function Connect(arg1:string,arg2:string):Promise<main.AppStatus>;

export function CopyText(arg1:string):Promise<void>;

export function CreateRoom(arg1:string,arg2:string):Promise<void>;

export function DeleteRoom(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function FormatInvite(arg1:string,arg2:string):Promise<string>;

export function GetPeers():Promise<Array<main.PeerInfo>>;

export function GetSavedRooms():Promise<Array<main.SavedRoomEntry>>;

export function GetSettings():Promise<main.ClientConfig>;

export function GetStatus():Promise<main.AppStatus>;

export function GetVersion():Promise<string>;

export function JoinRoom(arg1:string,arg2:string):Promise<void>;

export function LeaveRoom():Promise<void>;

export function LoadConfig():Promise<main.ClientConfig>;

export function OpenLogFolder():Promise<void>;

export function ParseInvite(arg1:string):Promise<Record<string, string>>;

export function PingPeer(arg1:string):Promise<void>;

export function Quit():Promise<void>;

export function RemoveSavedRoom(arg1:string):Promise<void>;

export function ResetSettings():Promise<main.ClientConfig>;

export function SaveConfig(arg1:main.ClientConfig):Promise<void>;

export function SaveRoom(arg1:string,arg2:string):Promise<void>;

export function SaveSettings(arg1:main.ClientConfig):Promise<boolean>;

export function SendChat(arg1:string,arg2:string):Promise<void>;

export function SetStartWithWindows(arg1:boolean):Promise<void>;
