// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate() {
  return window['go']['main']['App']['ApplyUpdate']();
}

export function BroadcastChat(arg1) {
  return window['go']['main']['App']['BroadcastChat'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function Connect(arg1, arg2) {
  return window['go']['main']['App']['Connect'](arg1, arg2);
}

export function CopyText(arg1) {
  return window['go']['main']['App']['CopyText'](arg1);
}

export function CreateRoom(arg1, arg2) {
  return window['go']['main']['App']['CreateRoom'](arg1, arg2);
}

export function DeleteRoom(arg1) {
  return window['go']['main']['App']['DeleteRoom'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function FormatInvite(arg1, arg2) {
  return window['go']['main']['App']['FormatInvite'](arg1, arg2);
}

export function GetPeers() {
  return window['go']['main']['App']['GetPeers']();
}

export function GetSavedRooms() {
  return window['go']['main']['App']['GetSavedRooms']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function JoinRoom(arg1, arg2) {
  return window['go']['main']['App']['JoinRoom'](arg1, arg2);
}

export function LeaveRoom() {
  return window['go']['main']['App']['LeaveRoom']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function OpenLogFolder() {
  return window['go']['main']['App']['OpenLogFolder']();
}

export function ParseInvite(arg1) {
  return window['go']['main']['App']['ParseInvite'](arg1);
}

export function PingPeer(arg1) {
  return window['go']['main']['App']['PingPeer'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RemoveSavedRoom(arg1) {
  return window['go']['main']['App']['RemoveSavedRoom'](arg1);
}

export function ResetSettings() {
  return window['go']['main']['App']['ResetSettings']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveRoom(arg1, arg2) {
  return window['go']['main']['App']['SaveRoom'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SendChat(arg1, arg2) {
  return window['go']['main']['App']['SendChat'](arg1, arg2);
}

export function SetStartWithWindows(arg1) {
  return window['go']['main']['App']['SetStartWithWindows'](arg1);
}
